listening-port=3478
listening-ip=127.0.0.1
relay-ip=192.168.200.27
external-ip=192.168.200.27
min-port=49160
max-port=49200
relay-threads=4
fingerprint
lt-cred-mech
realm=lingshan.local
user=lingshan:lingshan-a5-2026-7e91c
stale-nonce=600
no-cli
no-tls
no-dtls
no-multicast-peers
allowed-peer-ip=192.168.200.27
pidfile=/home/gmn/codes/cup/deploy/coturn/turnserver.pid
userdb=/home/gmn/codes/cup/deploy/coturn/turndb
simple-log
log-file=stdout
